### ISSUE TITLE
not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by zylee233** [jiangsutx/SRN-Deblur#30]
Traceback (most recent call last):
  File "run_model.py", line 50, in <module>
    tf.app.run()
  File "D:\Anaconda3\envs\tf18\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "run_model.py", line 42, in main
    deblur.test(args.height, args.width, args.input_path, args.output_path)
  File "F:\python\SRN-Deblur-master\models\model.py", line 282, in test
    h, w, c = blur.shape
ValueError: not enough values to unpack (expected 3, got 2)

If the Bit Resolution of a picture is 8, there will be error.
Then I change "blur = scipy.misc.imread(os.path.join(input_path, imgName))" to blur = scipy.misc.imread(os.path.join(input_path, imgName),mode='RGB') and solve it.

**Comment by siddharthapachhai** [comment]
I was having similar issues, I don't know if this is the Kendall answer, but I changed **scipy.misc.imread to cv2.i read in "model.py"**. I think Scipy doesn't read. 3 channels from some image files.

**Comment by jiangsutx** [comment]
I think your image has only one channel ?
Then you can use `--model=gray` and modify a little the code to process only one channel.

**Comment by zylee233** [comment]
There're three channels. This is the note of scipy.misc.imread.
   """
    Notes 
    -----
    `imread` uses the Python Imaging Library (PIL) to read an image.
    The following notes are from the PIL documentation.
    `mode` can be one of the following strings:
    * 'L' (8-bit pixels, black and white)
    * 'P' (8-bit pixels, mapped to any other mode using a color palette)
    * 'RGB' (3x8-bit pixels, true color)
    * 'RGBA' (4x8-bit pixels, true color with transparency mask)
    * 'CMYK' (4x8-bit pixels, color separation)
    * 'YCbCr' (3x8-bit pixels, color video format)
    * 'I' (32-bit signed integer pixels)
    * 'F' (32-bit floating point pixels)
    PIL also provides limited support for a few special modes, including
    'LA' ('L' with alpha), 'RGBX' (true color with padding) and 'RGBa'
    (true color with premultiplied alpha).
    When translating a color image to black and white (mode 'L', 'I' or
    'F'), the library uses the ITU-R 601-2 luma transform::
        L = R * 299/1000 + G * 587/1000 + B * 114/1000
    When `flatten` is True, the image is converted using mode 'F'.
    When `mode` is not None and `flatten` is True, the image is first
    converted according to `mode`, and the result is then flattened using
    mode 'F'.
    """

**Comment by zylee233** [comment]
> I think your image has only one channel ?
> Then you can use `--model=gray` and modify a little the code to process only one channel.

There're three channels, i'm sure.

**Comment by jiangsutx** [comment]
Actually, you can check `blur.shape` to see what exactly it is.
