### ISSUE TITLE
NameError: global name 'ResnetBlock' is not defined

### ISSUE THREAD

**Issue by JockeyLiao** [jiangsutx/SRN-Deblur#9]
你好，我编译报“NameError: global name 'ResnetBlock' is not defined”错误，请问是哪儿的问题，谢谢。
Traceback (most recent call last):
  File "run_model.py", line 53, in <module>
    tf.app.run()
  File "/Users/jockey/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "run_model.py", line 45, in main
    deblur.test(args.height, args.width, args.input_path, args.output_path)
  File "/Users/jockey/tensorflow/SRN-Deblur-master/models/model.py", line 271, in test
    outputs = self.generator(inputs, reuse=False)
  File "/Users/jockey/tensorflow/SRN-Deblur-master/models/model.py", line 93, in generator
    conv1_2 = ResnetBlock(conv1_1, 32, 5, scope='enc1_2')
NameError: global name 'ResnetBlock' is not defined

**Comment by firenxygao** [comment]
@JockeyLiao Please define the ResnetBlock within generator function with such piece of code:
def ResnetBlock(x, dim, ksize, scope='rb'):
            with tf.variable_scope(scope):
                net = slim.conv2d(x, dim, [ksize, ksize], scope='conv1')
                net = slim.conv2d(net, dim, [ksize, ksize], activation_fn=None, scope='conv2')
                return net + x

**Comment by JockeyLiao** [comment]
@firenxygao thank you,I found the function.
